### ISSUE TITLE
Is Foldmason indeed non-deterministic

### ISSUE THREAD

**Issue by jeversbioprodict** [steineggerlab/foldmason#15]
Hi,
It seems like every time I run `foldmason easy-msa` on the same pdbs, I get slightly different results.
Is this behaviour to be expected, and is there something I can do to prevent this from happening (eg, by setting a random seed).

If you need example code, please let me know!

**Comment by milot-mirdita** [comment]
Are you using the git version of foldmason? The issues should be fixed there. I think the initial release had this issue

**Comment by jeversbioprodict** [comment]
Not sure, is this sufficient information:
`foldmason Version: 63949d980645892a878c8427cbbd124b8dba425f`

**Comment by milot-mirdita** [comment]
Yes, thank you. That has a known issue that we fixed shortly after. You can download precompiled binaries for the latest git commit at https://mmseqs.com/foldmason/

**Comment by jeversbioprodict** [comment]
Amazing! Thank you so much :)

**Comment by jeversbioprodict** [comment]
That does the trick, cheers :)
