### ISSUE TITLE
MSA LDDT averaging 

### ISSUE THREAD

**Issue by tjmier** [steineggerlab/foldmason#6]
When calculating the MSA LDDT score foldmason sums the per-column average LDDT score then normalizes to the total number of columns. 

When a column contains only gaps other than one sequence it cannot have an LDDT score (hence the value -1 you get from grep-ing the scores in the html #4), however this column contributes to the total number of columns being normalized to so the average LDDT being reported smaller than you would expect.

Hypothetical Alignment
```
---AAA
CCCAAA
---AAA
```
Hypothetical average LDDT scores per column
`[-1,-1,-1,0.9,0.9,0.9]`

Expected MSA LDDT: 0.9
Reported MSA LDDT: 0.15

I am able to replicate this from my own analysis with foldmason when I pull the per-column LDDT scores from the html file. The reported msa LDDT score is normalized to the total number of columns despite whether or not they have an LDDT score.

Is this intentional?

**Comment by tjmier** [comment]
After thinking it over, I can see the merit in treating the single character columns as an LDDT score of 0. However, I think it could be useful to display the average of average LDDT score for all the columns as well as a score for the common core columns (gapless columns). A one off multidomain protein could drop the LDDT score significantly despite the rest of the alignment performing highly.

**Comment by gamcil** [comment]
Thank you for the feedback. Yeah, the idea was to still count non-scoring columns in the average LDDT in order to penalize super gappy MSAs, but reporting the common core score too would definitely have merit. Currently you can achieve this by adjusting `--pair-threshold` to exclude columns with a certain % of gap characters, but you have to run `msa2lddt` multiple times which is annoying - I think reporting multiple scores at different thresholds makes sense.

**Comment by tjmier** [comment]
One strategy that I've have been experimenting with is scoring the columns by taking the harmonic mean of the column occupancy and lddt score. This ensures that structurally homologous residues that are also present in the majority of structures are scored the highest. This ensure that columns that only contain a small amount of sequences with structurally homologous residues do not pollute the overall score.

You can also include a beta value to adjust the weight between lddt and occupancy, like what is done with F-score for precision and recall. To weight LDDT and occupancy equally beta would be set to 1. 

![CodeCogsEqn](https://github.com/user-attachments/assets/5ac4594a-6d44-4513-8156-31e8d001f334)

I wonder if the alignments would improve if this was used as the scoring function while constructing the alignments.

![image](https://github.com/user-attachments/assets/0b630587-02a7-4616-8295-80674f21dc25)

**Comment by igortru** [comment]
Could you , please, explain
why LDDT asymmetric in relation to first and second sequence inside pair?
 it is reasonable for original lDDT - reference vs model.
but for MSA it means , it depends on order of sequences in alignment
symmetric case can have higher LDDT, on my pairwis pdb test case : 1aab , 1j46 
- 0.74  asymmetric (query <= 15A) vs 0.77 symmetric , both <= 15A.

A 
B
not equal to
B 
A

                        **if (dists_to_score[query_idx1][query_idx2]) {**
                            float distance = dist(query_coordinates[query_idx1], query_coordinates[query_idx2]);
                            float dist_sub = dist(target_coordinates[align_to_target[align_idx1]],
                                                  target_coordinates[align_to_target[align_idx2]]);
                            float d_l = std::abs(distance - dist_sub);
                            float score = 0.25 * ((d_l < 0.5) + (d_l < 1.0) + (d_l < 2.0) + (d_l < 4.0));
                            reduce_score[align_idx2] += score;
                            reduce_score[align_idx1] += score;
                        }

**Comment by gamcil** [comment]
How did you calculate the scores here (0.74 vs 0.77)? Using `msa2lddt` on an alignment from `easy-msa` with 1aab and 1j46 I get 0.6 regardless of order in the file. The LDDT calculation is asymmetric but we pre-sort all of the sequences by their database index to remove the order dependency.

**Comment by tjmier** [comment]
Glad to see this method ended up being implemented in the final publication.

**Comment by martin-steinegger** [comment]
Thank you for the great suggestion!
