### ISSUE TITLE
No html output for easy-msa?

### ISSUE THREAD

**Issue by DaRinker** [steineggerlab/foldmason#9]
## Expected Behavior

Documentation says I can expect a "result.html" and a "result.fasta" 

## Current Behavior
Running foldmason version Version: 63949d980645892a878c8427cbbd124b8dba425f

Input pdb files were made by ESMfold (possibly relevant because ESMfold reports pLDDTs per-atom, unlike AF2)

Running the simple command:

`foldmason easy-msa <my pdbs> result.fasta tmpfolder
`
The output files I get are:

- result.fasta_3di.fa
- result.fasta_aa.fa
- result.fasta.nw

The resulting MSA looks good so not sure what's going on. Nor errors or exceptions reported.

**Comment by gamcil** [comment]
Looks like I need to update the docs - we turned off the LDDT calculation by default in `easy-msa`, to enable it again you can use `--report-mode 1` for HTML or `--report-mode 2` for JSON output (i.e. loadable in the server). If you have kept the structure database created in your last run (i.e. in `tmpfolder/latest/structures`), you could also directly use `msa2lddt` like:
```
# prints to console
msa2lddt tmpfolder/latest/structures result.fasta_aa.aa
# generate HTML report
msa2lddtreport tmpfolder/latest/structures result.fasta_aa.aa result.html
# generate JSON file
msa2lddtjson tmpfolder/latest/structures result.fasta_aa.aa result.json
```

**Comment by DaRinker** [comment]
Perfect. Works as expected. Thank you.
